version: '3'
# volumes:
#   mongodb:
#     external: true
# todo SETUP ENV VAR
services:
  # rebipp_database:
  #   image: mongo:latest
  #   container_name: "rebipp_database"
  #   environment:
  #     - MONGO_DATA_DIR=/data/db
  #     - MONGO_LOG_DIR=/dev/null
  #   volumes:
  #     - mongodb:/data/db
  #   ports:
  #       - 27017:27017
  #   command: mongod  --logpath=/dev/null     
  rebipp_app:
    build: ./
    # environment: 
      # - MONGODB_URI=mongodb://rebipp_database:27017/rebipp
      # - MONGODB_URI=mongodb+srv://qa:7FMoU3CD2Tyrv8en@qa.ksumv.mongodb.net/rebipp?retryWrites=true&w=majority
    volumes:
      - ./:/usr/src/app 
    command: bash -c "npm run serve /usr/src/app"    
    ports:
      - 3000:3000 
    # links:
    #   - rebipp_database
    # depends_on:
    #   - rebipp_database
